//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stelleracunakademiportfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_contact
    {
        public int contactID { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string Email { get; set; }
        public string MapUrl { get; set; }
    }
}
