//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stelleracunakademiportfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public int messageID { get; set; }
        public string Email { get; set; }
        public string NameSurname { get; set; }
        public string messageContent { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
