//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stelleracunakademiportfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_service
    {
        public int serviceID { get; set; }
        public string servicename { get; set; }
        public string serviceikon { get; set; }
        public Nullable<bool> servicestatus { get; set; }
    }
}
